### ISSUE TITLE
Fix issues raised by moodle-plugin-ci

### ISSUE THREAD

**Issue by daledavies** [daledavies/moodle-tool_registrationrules#10]
For example here... https://github.com/daledavies/moodle-tool_registrationrules/actions/runs/10813292679/job/29996978099?pr=4

There are numerous Moodle Code Checker and Moodle PHPDoc Checker errors.

**Comment by phager-at** [comment]
We should also state which Moodle CS we want to follow.

At eDaktik we strive to enforce standard Moodle coding style `moodle` of `moodlehq/moodle-cs` for new code and try to stick to Moodle's extended code style `moodle-extra` of `moodlehq/moodle-cs` as much as possible.

I propose we try to stick to `moodle-extra` as much as possible here to. What are your thoughts on it?

And further: how do we want to tackle bringing the code up to date with coding style? We'd have the option to clean up all code right now and develop new code using the strict standards or we'd clean up bit by bit as we have to touch code and the rest separately before publishing. Each of the approaches has pros and cons and I made the mistake of cleaning up everything on some legacy plugins in the past, but here we're still quite fresh and it should be easier to clean up.

**Comment by phager-at** [comment]
For clean ups of the whole plugin code base I usually stick to a single commit per rule I'd like to tackle, like one commit to add all the boilerplate comments, one commit to remove all occurences of two empty lines inside functions and methods, etc.

**Comment by daledavies** [comment]
The alternative might be a single `Fix Moodle CS` commit per file for all issues, which isn't great. Or multiple commits per file for each rule, which will be a lot of commits!

I think your approach is a good compromise :)

**Comment by daledavies** [comment]
I'm wondering if it wouldn't take too long to clear all the errors currently reported by the github action, as most of them look pretty simple. I'll see if I can do it this afternoon :)

**Comment by daledavies** [comment]
Are you working on this currently?

**Comment by phager-at** [comment]
Yes I started. But I can step aside, if you want. :joy:

**Comment by daledavies** [comment]
If you're already on it then I don't want to confuse things :)
