### ISSUE TITLE
Rejection points/scoring are not used

### ISSUE THREAD

**Issue by daledavies** [daledavies/moodle-tool_registrationrules#12]
Maybe implement this in `rule_checker::is_registration_allowed()`, I guess scoring needs to go into `rule_base` or `rule_check_result`.

Also need to implement fallback points.

Also I forgot what the "Invert rule" option is for.

**Comment by phager-at** [comment]
"Invert rule" was meant to invert the boolean outcome of the rule, so if a given rule evaluates to true for the current call/submission it would give no points as long as invert rule is active.

e.g. rule instance "disallow list" for IP address subnet "10.0.0.0/8" --> internal users would get denied. Activate invert rule, now only internal IPs are allowed to register. The disallow list becomes an allow list.
Or simpler: rule nope gets converted to a rule "yup" if invert rule is active

**Comment by daledavies** [comment]
> "Invert rule" was meant to invert the boolean outcome of the rule, so if a given rule evaluates to true for the current call/submission it would give no points as long as invert rule is active.
> 
> e.g. rule instance "disallow list" for IP address subnet "10.0.0.0/8" --> internal users would get denied. Activate invert rule, now only internal IPs are allowed to register. The disallow list becomes an allow list. Or simpler: rule nope gets converted to a rule "yup" if invert rule is active

This makes sense, thanks :)
