### ISSUE TITLE
Remove "move" and "hide/show" options from rule plugin management table

### ISSUE THREAD

**Issue by daledavies** [daledavies/moodle-tool_registrationrules#5]
Probably doesn't make sense to be able to both reorder and hide/show these, as we have those options via the rule instances page?

**Comment by phager-at** [comment]
The reorder and hide/show on plugin management could be used to determine:
1. the order in which those plugins appear to be added on rule instances page
2. which plugins appear to be addable on rule instances page
3. which plugins are enabled systemwide, regardless of how many instances of this type are added as rules, which could be used, if some subplugin contains some functionality breaking major bug and one likes to disable all rules of this type—but this may break the rest of the configuration (points for lockout never reached, etc.) unexpectedly if one's not attentive.

For now it won't make much difference. Real use cases may occur, if the plugin gets extended to be able to be added to any Moodleform. So IMHO a far-in-the-future benefit. We could add those again, if it occurs to us.

**Comment by daledavies** [comment]
Closing for now
