### ISSUE TITLE
Consistency in class and file names

### ISSUE THREAD

**Issue by daledavies** [daledavies/moodle-tool_registrationrules#8]
Some of our class and file names use underscores, some don't.

I'm actually unsure of the coding style rules for filenames of pages, whether these should include underscores. But class names should contain words separated by underscores.

So we should rename `ruleinstancescontroller` at the least, but it would be nice if we can standardise on a format for page filenames too.

Any thoughts?

**Comment by phager-at** [comment]
:+1: 

- proper class names
- proper namespace structure to have those class names maybe as short as possible, but as long as needed for clarity
- logical, precise and clear names for all entry points
